default_stages: [commit, manual]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml # Checks yaml files for parseable syntax.
          - id: check-json # Checks json files for parseable syntax.
          - id: check-added-large-files
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
#    - repo: https://github.com/sqlfluff/sqlfluff
#      rev: 1.3.2
#      hooks:
#        - id: sqlfluff-lint
#          args: ["dbt"]
          # For dbt projects, this installs the dbt "extras".
          # You will need to select the relevant dbt adapter for your dialect
          # (https://docs.getdbt.com/docs/available-adapters):
#          additional_dependencies: ['dbt-bigquery==1.2.0', 'sqlfluff-templater-dbt==1.3.2']
#        - id: sqlfluff-fix
          # Arbitrary arguments to show an example
          # args: [--rules, "L003,L014"]
          # additional_dependencies: ['dbt-bigquery==1.2.0', 'sqlfluff-templater-dbt']
    # - repo: https://github.com/bridgecrewio/checkov.git
    #   rev: '2.1.61'
    #   hooks:
    #     -   id: checkov
    #         name: Checkov
    #         description: This hook runs checkov.
    #         entry: checkov -d .
    #         language: python
    #         pass_filenames: false
    #         always_run: false
    #         files: \.tf$
    #         exclude: \.+.terraform\/.*$
    #         require_serial: true

